services:
  webui:
    container_name: sd-intel-webui
    build: ./services/webui/
    profiles: ["webui"]
    ports:
      - "7860:7860"
    volumes:
      - "./models:/stable-diffusion-webui/models"
      - "./extensions:/stable-diffusion-webui/extensions"
      - "./outputs:/stable-diffusion-webui/outputs"
      - "./config:/stable-diffusion-webui/config"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    environment:
      - CLI_ARGS=--allow-code --enable-insecure-extension-access
    restart: unless-stopped

  download:
    build: ./services/download/
    profiles: ["download"]
    volumes:
      - "./models:/stable-diffusion-webui/models"
